require 'yaml'
require 'forwardable'
require 'singleton'

require 'rubygems'
require 'i18n'
require 'locale'
require 'deep_merge'
require 'pastel'

require_relative 'constants'
require_relative 'validator'
require_relative 'mixin'
require_relative 'container'
require_relative 'helpers'
require_relative 'configuration'

require_relative 'registry_file'
require_relative 'registry'
require_relative 'services/init'
