---
:myappli:
  :production: {}
  :staging:
    :onstaging: staging
  :test: {}
  :development:
    :ondev: test
    :treeA:
      :trunk1:
        :branch1: leaf1
      :trunk2:
        :branch3: leaf3
        :branch4: leaf4
        :branch5: [ "val1","val2","val3" ] 
  :default:
    :default_value: 'value'
    :treeA:
      :trunk1:
        :branch2: leaf2
      :trunk2:
        :branch5: ["value"]
    :setup:
      :rules:
        - :action: :install_file
          :source: "samples/config/settings.yml"
          :target: "/tmp/settings.yml"
        - :action: :install_file
          :source: "samples/config/carioca.registry"
          :target: "/tmp/carioca.registry"
          :mode: "755"
        - :action: :make_folder
          :path: /tmp/toto
        - :action: :make_link
          :source: /tmp/settings.yml
          :link: /tmp/application.yml