---
:monappli:
  :production: {}
  :staging:
    :onstaging: staging
  :test: {}
  :development:
    :ondev: test
    :treeA:
      :trunk1:
        :branch1: leaf1
      :trunk2:
        :branch3: leaf3
        :branch4: leaf4
        :branch5: [ "toto","titi","tata" ] 
  :default:
    :toto: 'titi'
    :treeA:
      :trunk1:
        :branch2: leaf2
      :trunk2:
        :branch5: ["tutu"]

    
